### ISSUE TITLE
Instrument is_authorized to determine where time is going

### ISSUE THREAD

**Issue by skuenzli** [k9securityio/cedar-py#14]
We've opened #13 to discuss how to optimize similar `is_authorized` API calls.  

However, I don't think we have a good sense of where the time is going other than it's generally _not_ going into the [Cedar `Authorizor#is_authorized`](https://github.com/k9securityio/cedar-py/blob/main/src/lib.rs#L257) method, which generally executes in a few hundred microseconds.  We might find a material portion of is_authorized execution time isn't being spent in Rust code at all, which will change how we optimize.

So let's instrument `is_authorized` and record the following metrics to find out:

* total_duration_micros
* load_schema_duration_micros
* load_entities_duraiton_micros
* ... etc..

**Comment by andrewmwells-amazon** [comment]
Seems reasonable. From my experience, time on the Rust side is mostly spent:
1) Serializing / deserializing from JSON
2) Building the `Evaluator` object if you have many entities / complex entities. This can be fixed with entity slicing or hopefully with a feature such as https://github.com/cedar-policy/rfcs/pull/14 if you're making repeated queries.
3) Deep policies can require a lot of recursion. Not sure if you've run into this yet

**Comment by skuenzli** [comment]
Thanks @andrewmwells-amazon !  That's very helpful in guiding instrumentation and optimization efforts.

re 'deep policies':
Can you say more about 'deep policies' are or recommend what metrics we should track about policies?  

I was planning to record the counts of policies and entities

**Comment by andrewmwells-amazon** [comment]
> Thanks @andrewmwells-amazon ! That's very helpful in guiding instrumentation and optimization efforts.
> 
> re 'deep policies': Can you say more about 'deep policies' are or recommend what metrics we should track about policies?
> 
> I was planning to record the counts of policies and entities

By that I mean policies like:
`permit(principal, action, resource) when {principal.foo1 && principal.foo2 && ... && principal.foo1000};`
I haven't heard of any issues with "natural" examples, but this came up when generating some synthetic tests.

**Comment by skuenzli** [comment]
Implemented in #16
