### ISSUE TITLE
RFC: Should `is_authorized` return a `dict` or a fully-modeled object instance, e.g. `AuthzResult`?

### ISSUE THREAD

**Issue by skuenzli** [k9securityio/cedar-py#7]
Should `is_authorized` return a `dict` or a fully-modeled object instance, e.g. `AuthzResult`?

The `cedar` authorization engine helpfully provides quite a bit of context about an authorization decision.  And we're also interested in metrics so that we can understand the performance implications of integration, policy-modeling, and other decisions.

`is_authorized` currently returns a dict that looks like:

```
    {
        "decision": "Allow|Deny",
        "diagnostics": {
            "reason": ["policy0"], # the policy that determined the decision
            "errors": []           # any errors
        },
        "metrics": {
            "authz_duration_micros": 42
        }
    }
```

Providing an authorization result as a `dict` has some advantages: 

1. all consumers know how to work with `dict`
2. most people developing in Python for AWS are probably accustomed to unpacking `boto3`'s `dict` responses
3. we can add data easily without the 'overhead' of defining and using classes both from a development and a runtime execution perspective
4. dicts are easy to mock in unit tests, which might be a common use case for testing various policy decision scenarios

But there are some disadvantages:
1. users have to know the object structure and match on string values like `Allow` (not 'ALLOW'  or 'allow' or something in between) to use the results; (I've already made this mistake in the README, no less)
2. in general, users have to guess which values might be present in e.g. metrics

We could try to solve some of these problems by introducing some basic classes & enums to model the domain:
* AuthzResult (class)
* Decision (enum)
* Diagnostics (class) probably not much more than a wrapper around the diagnostics member object
* Metrics (class) probably not much more than a wrapper around the diagnostics member object, plus maybe a list of well-known metric names and possibly getters that have the expected return type

(likely very similar to `cedar-java`'s [`AuthorizationResult`](https://github.com/cedar-policy/cedar-java/blob/main/CedarJava/src/main/java/cedarpolicy/model/AuthorizationResult.java))

Some (expected) advantages:
1. The cedar-authz domain should be easier to learn and adopt correctly, especially for evaluating the decision result because users can navigate and test access using the domain model `if Decision.Allow == authz_result.decision`
2. The `cedar-py` library may/can provide a more stable interface than a bare `dict`

Some (expected/possible) disadvantages:
1. Will there be significant runtime overhead? (probably not... but we could test)
2. The cedar-py rust code returns a json-formatted string object and that won't be changing in the near future. Do we provide (public) access to an `is_authorized` function that returns the underlying authz response as a dict (the current interface) in addition to the one bound to the domain?

**Comment by glb** [comment]
Not strongly opinionated; it feels like there are valid reasons to go in either direction. While the raw `dict` is pretty reminiscent of the AWS SDK, it's possible that someone could want to use `cedar-py` in a project that doesn't use AWS at all and uses types.

Also, while having a typed object and a decision enum would be helpful for someone using an editor that can prompt them with suggestions, the interface is not particularly large at the moment and the example code in the [Using the library](https://github.com/k9securityio/cedar-py#using-the-library) section of the README was enough for me to try it out and understand what needed to be done / what was available.

Do you expect the interface to grow significantly?

Perhaps a terrible idea: what about both? Is that the worst of both worlds? 

<details>
<summary>Incomplete example</summary>

I'm not a Python expert, so this example is likely wrong in multiple ways.

```
class AuthzResult(dict):
    def __init__(self,*arg,**kw):
        super(AuthzResult, self).__init__(*arg, **kw)

    def __getattribute__(self, __name: str) -> Any:
        # wrap metrics dict in a class that exposes the contents as attributes
        if __name == "metrics":
            return x(self['metrics'])
        # synthesize an `allowed` boolean attribute for convenience
        if __name == "allowed":
            return self['decision'] == 'Allow'
        # expose dict content as attributes
        if __name in self:
            return self[__name]

        # fall back to superclass
        return super(AuthzResult, self).__getattribute__(__name)

    # support tab-completion for iPython
    def __dir__(self):
        # add the synthetic attribute `allowed` to the list
        return list(self.keys()) + ['allowed']

class x(dict):
    def __init__(self, *arg, **kw):
        super(x, self).__init__(*arg, **kw)

    def __getattribute__(self, __name: str) -> Any:
        # expose dict content as attributes
        if __name in self:
            return self[__name]
        return super(x, self).__getattribute__(__name)

    # support tab-completion for iPython
    def __dir__(self):
        return self.keys()
```

```
result = cedarpolicy.is_authorized(request, policies, entities)

print(json.dumps(result))
# {"decision": "Allow", "diagnostics": {"reason": ["policy0"], "errors": []}, "metrics": {"authz_duration_micros": 99}}
print(result.allowed)
# True
print(result.decision)
# Allow
print(result['decision'])
# Allow
print(result.metrics.authz_duration_micros)
# 99
print(result['metrics']['authz_duration_micros']
# 99
```

</details>

**Comment by skuenzli** [comment]
Thanks for the feedback and example!  

I have been thinking about a thin wrapper around the underlying dict that returns typed instances, particularly for `decision` and `diagnostics`.  I think your example is the logical conclusion of that.  It's a nice starting point I'll use for experiments this morning.

re types or not:
The main goal is to prevent errors checking access.  So at a minimum, I'm thinking of a `Decision` type.

I think there are also some advantages to following the lead of `cedar-java` which has types (of course).  One nice thing they did is they corrected the plurality of diagnostics' `reason` member to `reasons` since it is an array.

**Comment by glb** [comment]
Thanks! Another option that occurs to me now is that you could translate the decision into a boolean way down at the Rust level and avoid the `Decision` enum altogether; maybe a discussion point with the Cedar folks about the future they envision for that and why they chose to use an enum.

**Comment by skuenzli** [comment]
:) I often feel penned-in by boolean values as the result of a decision. (also wrote Java for ~15 years)

Sort of interestingly...

Cedar (Rust) defines [`Decision`](https://github.com/cedar-policy/cedar/blob/main/cedar-policy-core/src/authorizer.rs#L870) with `Allow` and `Deny` values

cedar-java defines [`Decision`](https://github.com/cedar-policy/cedar-java/blob/main/CedarJava/src/main/java/cedarpolicy/model/AuthorizationResult.java#L36) with `Allow`, `Deny`, and `NoDecision` values

**Comment by glb** [comment]
For clarity: I'm not deeply opinionated here, just exploring and perhaps splitting hairs.

> :) I often feel penned-in by boolean values as the result of a decision. (also wrote Java for ~15 years)

Interesting. I'm coming at it from the perspective of the caller trying to make a go / no-go decision. Totally makes sense if there's an exceptional case that needs special handling, but does that warrant making the job harder for the consumer?

> Cedar (Rust) defines [Decision](https://github.com/cedar-policy/cedar/blob/main/cedar-policy-core/src/authorizer.rs#L870) with Allow and Deny values
>
> cedar-java defines [Decision](https://github.com/cedar-policy/cedar-java/blob/main/CedarJava/src/main/java/cedarpolicy/model/AuthorizationResult.java#L36) with Allow, Deny, and NoDecision values

_Very_ interesting on the Java side. I asked in `#cedar-core` and they said "Keeping it to Allow/Deny is a \[tenet] of ours". The assertion was that they made it an enum in Rust "purely for the sake of explicitness, type safety, and \[ease] of implementing traits for it."

I get how in Rust pattern-matching is neat, but am not sure that extends nicely to Python. I am perfectly fine writing a wrapper that gives me the behaviour I'm thinking of if you want to keep fidelity with the underlying Rust code. Some form of wrapper is almost inevitable anyway given the multitude of ways to determine principal, action, resource, and context, pass them to the `is_authorized` call, and handle the results.

**Comment by skuenzli** [comment]
> Interesting. I'm coming at it from the perspective of the caller trying to make a go / no-go decision. Totally makes sense if there's an exceptional case that needs special handling, but does that warrant making the job harder for the consumer?

I think there's a lot of value in an `allowed` method/property.  That's definitely going in.

Here's what I built in https://github.com/k9securityio/cedar-py/pull/10
```
authz_result: AuthzResult = is_authorized(...)

# check result's decision property against the Decision enum
if Decision.Allow == authz_result.decision
   ...

# or... use the allowed convenience property:
if authz_result.allowed
```

FWIW, I spent the morning trying to get a `__getattribute__` / `__getattr__` impl going this morning.  The main issue is that I want `authz_result['decision']` to return the Decision enum.  But if when extending `dict`, `authz_result['decision']` always returned 'Allow'.  The nominal problem was that the AuthzResult `__getattribute__` impl wasn't being called.  My Python skills aren't good enough to sort that out today and I was going down a hole.  So adopted a simpler implementation with subscripting support.

**Comment by skuenzli** [comment]
Geoff had a nice suggestion for an `AuthzResult` class that extends `dict` that would/should solve the `decision` property problem:
```
    def __getitem__(self, __key: Any) -> Any:
        if __key == "decision":
            return Decision[super().__getitem__(__key)]

        return super().__getitem__(__key)
```

We can definitely consider this solution.  Though I also want to think about what it means for someone to _set_ a property on `AuthzResult`

**Comment by skuenzli** [comment]
Closing. @glb - thank you for your feedback!

**Comment by glb** [comment]
> Though I also want to think about what it means for someone to set a property on AuthzResult

Setting properties on an `AuthzResult` is probably not a meaningful thing for someone to do; I'd be super-curious what a person was intending if they wanted to do that.

Your implementation is great & I think makes it super-clear that the `AuthzResult` is meant to be immutable. A person could keep adding hacks to my suggestion (implement `__setitem__` / `__setattr__` to raise an exception, for example), but at some point I'd look at all the hacks and caution tape and say "hmm maybe Stephen was on the right path" 🙂

**Comment by skuenzli** [comment]
Super - let's call this 'done' for now.  When new use cases arise, we will consider adjusting the impl.
